---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.deployment" . }}-client
  namespace: {{ .Values.namespace}}
  label:
    app: {{ include "helm.deployment" . }}-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm.deployment" . }}-client
  template:
    metadata:
      labels:
        app: {{ include "helm.deployment" . }}-client
    spec:
      serviceAccount: {{ .Values.namespace}}
      containers:
        - name: {{ include "helm.deployment" . }}-client
          image: "{{- .Values.image.repository -}}/{{- .Values.image.name -}}:{{- .Values.branch.actual -}}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.ressources | nindent 12 }}
