---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.deployment" . }}-client
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ include "helm.deployment" . }}-client
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ include "helm.deployment" . }}-client
  type: ClusterIP
