# Default values for kube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project:
  name: portfolio
  env:
    - prod
    - dev
  service:
    - client
#    - api

client:
  prod:
    branch: master
    tag: latest
    port: 80
    path: /
  dev:
    branch: develop
    tag: Latestdev
    port: 80
    path: /

api: {}
#   prod:
#     path: /api
#     tag: latest
#     port: 3001
#     branch: master
#   dev:
#     branch: develop
#     tag: Latestdev
#     path: /api
#     port: 3001

db: {}
#   prod:
#     image: mongo
#     tag: latest
#     port: 27017
#     user: pos-prod
#     pass: posPasswordProd
#     dbname: POSprod
#   dev:
#     image: mongo
#     tag: latest
#     port: 27017
#     user: pos-dev
#     pass: posPasswordDev
#     dbname: POSdev

server:
  domain:
    prod:
      name: weebo.fr
      ssl: weebo-tls
    dev:
      name: portfolio.dev.weebo.fr
      ssl: portfolio-dev-weebo-tls
  certIssuer: "letsencrypt-prod"
  ingressClassName: nginx
  registry: harbor.weebo.fr
