{{ range $key, $val := .Values.db -}}
{{- with $ -}}
{{ if has $key .Values.project.env }}
{{- $deployName := printf "%s-db-%s-deploy" .Values.project.name $key -}}
{{- $configclient := printf "%s-db-%s-configmap" .Values.project.name $key -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$deployName}}
  namespace: {{.Values.project.name}}
  labels:
    app: {{$deployName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$deployName}}
  template:
    metadata:
      labels:
        app: {{$deployName}}
    spec:
      volumes:
        - name: mogopvc
          persistentVolumeClaim:
            claimName: {{ printf "%s-db-%s-pv-claim" .Values.project.name $key }}
      containers:
        - name: {{$deployName}}
          image: {{ printf "%s:%s" $val.image $val.tag}}
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{$val.user}}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{$val.pass}}
            - name: MONGO_INITDB_DATABASE
              value: {{$val.dbname}}
          ports:
            - name: http
              containerPort: {{$val.port}}
          volumeMounts:
            - mountPath: /data/db
              name: mogopvc
          readinessProbe:
            httpGet:
              path: {{$val.path}}
              port: {{$val.port}}
{{ end }}
{{ end }}
{{ end }}