{{ range $key, $val := .Values.api -}}
{{- with $ -}}
{{ if has $key .Values.project.env }}
{{- $deployName := printf "%s-api-%s-deploy" .Values.project.name $key -}}
{{- $configApi := printf "%s-api-%s-configmap" .Values.project.name $key -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$deployName}}
  namespace: {{.Values.project.name}}
  labels:
    app: {{$deployName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$deployName}}
  template:
    metadata:
      labels:
        app: {{$deployName}}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{$deployName}}
          image: {{ printf "%s/%s/api:%s" .Values.server.registry .Values.project.name $val.tag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{$val.port}}
          readinessProbe:
            httpGet:
              path: {{printf "%s/" $val.path}}
              port: {{$val.port}}
{{ end }}
{{ end }}
{{ end }}