{{- range $key,$val := .Values.server.domain }}
{{- with $ }}
{{ if has $key .Values.project.env}}
{{- $ingressName := printf "%s-%s-ingress" .Values.project.name $key -}}
#{{- $configApi := get .Values.api $key -}}
{{- $configclient := get .Values.client $key -}}
#{{- $serviceApi    := printf "%s-api-%s-service" .Values.project.name $key -}}
{{- $serviceclient := printf "%s-client-%s-service" .Values.project.name $key -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{$ingressName}}
  namespace: {{ .Values.project.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.server.certIssuer}}
spec:
  ingressClassName: {{ .Values.server.ingressClassName}}
  tls:
    - hosts:
      - {{ $val.name | quote}}
      secretName: {{ $val.ssl }}
  rules:
    - host: {{ $val.name }}
      http:
        paths:
          - path: {{$configclient.path}}
            pathType: Prefix
            backend:
              service:
                name: {{$serviceclient}}
                port:
                  number: {{$configclient.port}}
{{- end }}
{{- end }}
{{- end }}