apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci
  namespace: {{.Values.project.name}}
subjects:
- kind: ServiceAccount
  name: concourse
roleRef:
  kind: Role
  name: role-ci
  apiGroup: rbac.authorization.k8s.io