{{ range .Values.project.service -}}
{{ $toDeploy := .}}
{{- with $ -}}
{{$appToDeploy := get .Values $toDeploy}}
{{- range $key,$val := $appToDeploy -}}
{{- with $ -}}
{{if has $key .Values.project.env}}
{{- $appDeploy := printf "%s-%s-%s-deploy" .Values.project.name $toDeploy $key -}}
{{- $appService := printf "%s-%s-%s-service" .Values.project.name  $toDeploy $key -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$appService}}
  namespace: {{.Values.project.name}}
  labels:
    app: {{$appService}}
spec:
  ports:
    - name: http
      port: {{$val.port}}
      targetPort: {{$val.port}}
  selector:
    app: {{$appDeploy}}
  type: ClusterIP
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}