apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bpg-pipeline
  namespace: batleforc-portfolio
spec:
  description: |
    This pipeline builds batleforc Portfolio.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: repo-branch
      type: string
      default: main
      description: The git repo branch to clone from.
    - name: repo-revision
      type: string
      default: main
      description: The git repo revision to clone from.
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
    - name: dockerconfig
      description: |
        This workspace contains the docker config.json file, so it can be used by
        the next task.
    - name: kubeconfig
      description: |
        This workspace contains the kubeconfig file, it define the namespace to rollout.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
    - name: build-docker
      runAfter: ["fetch-source"]
      taskRef:
        name: build
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: path-dockerfile
          value: ./client/
        - name: context-dockerfile
          value: ./client
        - name: IMAGE
          value: batleforc/portfolio
        - name: repo-branch
          value: $(params.repo-branch)
    - name: rollout
      runAfter: ["build-docker"]
      taskRef:
        name: kubernetes-actions
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig
      params:
        - name: script
          value: |
            kubectl rollout restart deploy prod-client -n batleforc-portfolio
