apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bpg-pipeline
  namespace: batleforc-portfolio-cicd
spec:
  description: |
    This pipeline builds batleforc Portfolio.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: repo-branch
      type: string
      default: main
      description: The git repo branch to clone from.
    - name: repo-revision
      type: string
      default: main
      description: The git repo revision to clone from.
  workspaces:
    - name: shared-data
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
    - name: build-docker
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: DOCKERFILE
          value: ./client/Dockerfile
        - name: CONTEXT
          value: ./client
        - name: IMAGE
          value: habror.weebo.fr/batleforc/portfolio:$(params.repo-branch)
