apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bpg-pipeline-template
  namespace: batleforc-portfolio-cicd
spec:
  params:
    - name: gitrevision
      description: The git revision (SHA)
      default: master
    - name: gitbranch
      description: The git branch
      default: master
    - name: gitrepositoryurl
      description: The git repository url ("https://github.com/batleforc/portfolio")
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: bpg-pipeline-run-
      spec:
        pipelineRef:
          name: bpg-pipeline
        workspace:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: gitrevision
            value: $(tt.params.gitrevision)
          - name: repo-branch
            value: $(tt.params.gitbranch)
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
