name: ci master
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - uses : actions/checkout@v2
      - run : pwd
      - run : echo "$test" > ./API/Config.all.js
        shell : bash
        env:
          test: ${{secrets.TEST}}
      - run : docker build -t batlefroc/portfolio .
      - run : docker container stop ${{secrets.CONTAINER_NAME}}
        continue-on-error: true
      - run : docker container rm portfolio
        continue-on-error: true
      - run : docker run -p 8080:8080 -d --network weebo --name ${{secrets.CONTAINER_NAME}} batlefroc/portfolio
      - run : docker logs portfolio